name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: |
          mkdir -p dist
          npm run build
          
      # Only run for releases
      - name: Prepare release asset
        if: github.event_name == 'release'
        run: |
          cp dist/ember-mug-card.js ./ember-mug-card.js
          
      - name: Upload release asset
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: ember-mug-card.js
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: ember-mug-card
          path: dist/ember-mug-card.js
          
  release:
    needs: build
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ember-mug-card
          path: dist
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/ember-mug-card.js
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
